sp:
  user-service:
    users: "[{\"id\":1111, \"username\":\"zzzzzzzz\",\"password\":\"2222222\"},{\"id\":777, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"},{\"id\":99, \"username\":\"aaasdasdc\",\"password\":\"12123123\"}]"

spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.64.5
    port: 5672
    username: admin
    password: admin
    
server:
  port: 8101
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka1:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh
